# Chi Zhang
### 08/11/2020
# Daily-exercise-06

```{r}
library(tidyverse)

url = 'https://raw.githubusercontent.com/nytimes/covid-19-data/master/us-counties.csv'

covid = read_csv(url)
```

### Question 1

```{r}
covid %>%
  filter(date == max(date)) %>%
  group_by(state) %>%
  summarize(cases = sum(cases, na.rm = TRUE)) %>%
  ungroup() %>%
  slice_max(cases, n = 6) %>%
  pull(state) ->
  top_states
  
filter(covid, state %in% c("California", "Florida", "Texas", "New York", "Georgia", "Illinois")) %>%  
  group_by(state, date) %>%
  summarise(cases = sum(cases)) %>%
  ungroup() %>%
  ggplot(aes(x = date, y = cases)) +
  geom_line(aes(color = state)) +
  labs(title = "6 States with Most Cases: COVID-19 Pandemic",
       x = "Date",
       y = "Everyday Cases",
       caption = "based on https://raw.githubusercontent.com/nytimes/covid-19-data/master/us-counties.csv",
       subtitle = 'Data Source: Covid',
       color = "") +
  facet_wrap(~state) +
  theme_gray() 

```

### Question 2

```{r}
covid %>%
  group_by(date) %>%
  summarise(cases = sum(cases, na.rm = TRUE)) %>%
  ungroup() %>%
  ggplot(aes(x = date, y = cases)) +
  geom_col(color = "red") +
  labs(title = "National Cummulative Case Counts: COVID-19 Pandemic",
       x = "Date",
       y = "Everyday Cases",
       caption = "based on https://raw.githubusercontent.com/nytimes/covid-19-data/master/us-counties.csv",
       subtitle = 'Data Source: Covid',
       color = "") +
  theme_gray()

ggsave(gg, file = "img/question 2.png")
```



